### ISSUE TITLE
Exception while compiling

### ISSUE THREAD

**Issue by aliyildiz1980** [dkimitsa/robovm-robopods#21]
I get the following exception while compiling my project. The error occurs only in 1.31.0-SNAPSHOT and 1.32.0-SNAPSHOT. 

I compile using Android Studio Flamingo 2022.2.1 and MobiVM plugin v2.3.19

Altpods I use are firebase-google-mobile-ads, firebase-auth, firebase-firestore, firebase-storage, firebase-remote-config

ERROR] Couldn't compile app
java.lang.IllegalArgumentException: No @Marshaler found for return type of @Bridge method <org.robovm.pods.firebase.firestore.FIRFirestoreSettings: java.lang.Object $m$cacheSettings(org.robovm.pods.firebase.firestore.FIRFirestoreSettings,org.robovm.objc.Selector)>
	at org.robovm.compiler.MarshalerLookup.findMarshalerMethod(MarshalerLookup.java:169)
	at org.robovm.compiler.BroMethodCompiler.getReturnType(BroMethodCompiler.java:454)
	at org.robovm.compiler.BroMethodCompiler.getBridgeOrCallbackFunctionType(BroMethodCompiler.java:534)
	at org.robovm.compiler.BroMethodCompiler.getBridgeFunctionType(BroMethodCompiler.java:526)
	at org.robovm.compiler.BridgeMethodCompiler.doCompile(BridgeMethodCompiler.java:292)
	at org.robovm.compiler.AbstractMethodCompiler.compile(AbstractMethodCompiler.java:79)
	at org.robovm.compiler.ClassCompiler.compileMethod(ClassCompiler.java:1540)
	at org.robovm.compiler.ClassCompiler.bridgeMethod(ClassCompiler.java:1558)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:862)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:301)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:341)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:427)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:506)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:957)
	at org.robovm.idea.compilation.RoboVmCompileTask$3.doCompile(RoboVmCompileTask.java:277)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)

**Comment by dkimitsa** [comment]
hi, just to save time, could you please share you gradle strings where you includes alt-pods and sample code to reproduce.
thxs!

**Comment by aliyildiz1980** [comment]
Here is the sample project. I removed Firebase SDK (v10.11.0) libs (located under ios/libs/arm and ios/libs/sim) to decrese project size.

altpodsVersion = '1.31.0-SNAPSHOT'


implementation "io.github.dkimitsa.robovm:robopods-firebase-google-mobile-ads-ios:$altpodsVersion"
implementation "io.github.dkimitsa.robovm:robopods-firebase-auth-ios:$altpodsVersion"
implementation "io.github.dkimitsa.robovm:robopods-firebase-firestore-ios:$altpodsVersion"
implementation "io.github.dkimitsa.robovm:robopods-firebase-storage-ios:$altpodsVersion"
implementation "io.github.dkimitsa.robovm:robopods-firebase-remote-config-ios:$altpodsVersion"

[AltpodTest.zip](https://github.com/dkimitsa/robovm-robopods/files/11925955/AltpodTest.zip)

**Comment by dkimitsa** [comment]
hi @aliyildiz1980 
have tested your code (with 2.3.20-SNAPSHOT but it should work with 2.3.19) and compiled it without any issues:
```
[INFO] 12:42:40.339 Compiling org.robovm.pods.firebase.firestore.FIRFirestore$$BlockMarshaler4 (ios arm64-simulator release)
[INFO] 12:42:40.349 Compiling org.robovm.pods.firebase.firestore.FIRFirestoreSettings (ios arm64-simulator release)
[INFO] 12:42:40.356 Compiling org.robovm.pods.firebase.firestore.FIRListenerRegistration (ios arm64-simulator release)
```

are you compiling directly from Android Studio using MobiVM plugin v2.3.19 ? Or invoke gradle script from command line ? 
can you please share entire build log from "RoboVM" tool window ? 
also "Cleaning global RoboVM" cache might help.
This

**Comment by dkimitsa** [comment]
ok, it happens with alt-pods 1.32.0 due added following fields 
```
    @Property(selector = "cacheSettings")
    public native <T0 extends Object & FIRLocalCacheSettings & NSObjectProtocol> T0 getCacheSettings();
    @Property(selector = "setCacheSettings:")
    public native <T0 extends Object & FIRLocalCacheSettings & NSObjectProtocol> void setCacheSettings(T0 v);
```

will check, thxs !

**Comment by aliyildiz1980** [comment]
Hi,

I build using android studio plugin. The build log with 1.31.0-SNAPSHOT is attached
[build_log.txt](https://github.com/dkimitsa/robovm-robopods/files/11929234/build_log.txt)

**Comment by dkimitsa** [comment]
have fixed and deployed under same version
(just refresh gradle dependencies)
here is a commit
https://github.com/dkimitsa/robovm-robopods/commit/09d453715ba85512fed3bb1f67882df37b77be8f

**Comment by aliyildiz1980** [comment]
İt worked. Thanks
