### ISSUE TITLE
Create IPA issue

### ISSUE THREAD

**Issue by WillCalderwood** [dkimitsa/robovm-robopods#6]
I've just switched to using Altpods to build with the latest SDKs and everything works fine running and testing on a device and in the simulator, but when I create an IPA I get the following error. Any ideas what's going on?

```
[ERROR] Couldn't create IPA
java.lang.IllegalArgumentException: No @Marshaler found for return type of @Bridge method <org.robovm.pods.google.mobileads.GADRequest: org.robovm.apple.uikit.UIWindowScene $m$scene(org.robovm.pods.google.mobileads.GADRequest,org.robovm.objc.Selector)>
	at org.robovm.compiler.MarshalerLookup.findMarshalerMethod(MarshalerLookup.java:169)
	at org.robovm.compiler.BroMethodCompiler.getReturnType(BroMethodCompiler.java:451)
	at org.robovm.compiler.BroMethodCompiler.getBridgeOrCallbackFunctionType(BroMethodCompiler.java:531)
	at org.robovm.compiler.BroMethodCompiler.getBridgeFunctionType(BroMethodCompiler.java:523)
	at org.robovm.compiler.BridgeMethodCompiler.doCompile(BridgeMethodCompiler.java:291)
	at org.robovm.compiler.AbstractMethodCompiler.compile(AbstractMethodCompiler.java:77)
	at org.robovm.compiler.ClassCompiler.compileMethod(ClassCompiler.java:1512)
	at org.robovm.compiler.ClassCompiler.bridgeMethod(ClassCompiler.java:1530)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:864)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:297)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:309)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:392)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:452)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:784)
	at org.robovm.idea.compilation.RoboVmCompileTask$1.doCompile(RoboVmCompileTask.java:123)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
```

**Comment by dkimitsa** [comment]
hi, what version of Idea plugin are you using ? 
Thx

**Comment by WillCalderwood** [comment]
I was running 2.3.5. I've just updated to 2.3.10 and that's resolved it. Thanks for the pointer.
